Connections
SimCorp/nats-topology-visualiser pull request #26
Opened 2021-03-20 11:49 UTC by KirstineBerg

Added features so connections, routes and gateways are now added to their correct servers.

2021-03-20 21:58 UTC, pizzaluc requested changes

2021-03-20 21:58 UTC, pizzaluc commented on backend/Program.cs
> +            Parallel.ForEach(Connections, c =>
can we rename c, r and g to the appropriate names?

and use concurrent safe lists

2021-03-20 21:58 UTC, pizzaluc commented on backend/Program.cs
> +            Connections.Add(connection);
we should probably move this `Connections.Add(connection);` inside the try statement, thats my bad, otherwise we might add an empty connection object

2021-03-21 10:29 UTC, tjomson approved these changes
I made the adjustments that i think were needed, so it looks good now

2021-03-21 10:32 UTC, tjomson commented on backend/Program.cs
> +            Parallel.ForEach(Connections, c =>
Resolved by commit 6836061 and aecd476

2021-03-21 10:33 UTC, tjomson commented on backend/Program.cs
> +            Connections.Add(connection);
Resolved by commit aecd476

2021-03-21 10:47 UTC, pizzaluc approved these changes
Looks good!

2021-03-22 09:13 UTC, Maasdamind reviewed
Looks great! just a few things I noticed 👍 

I also notice that we switch a great deal between using `snake_case` and `camelCase` for our variables, which makes the code look a bit more messy. Should we agree to use one or the other? Personally i prefer `camelCase` unless it is a really long name (Like a test name `should_return_value_when_doing_thing`) as that makes them a lot easier to read

2021-03-22 09:13 UTC, Maasdamind commented on backend/Controller.cs
> +        public ActionResult<IEnumerable<Connection>> Get_Connz()
Is there a reason we are not using camel case here as the only place?

2021-03-22 09:13 UTC, Maasdamind commented on backend/Program.cs
> +        public static ConcurrentBag<Gateway> GateWays = new ConcurrentBag<Gateway>();
These should probably not be capital first, like `serverMap`

2021-03-22 13:54 UTC, tjomson commented on backend/Program.cs
> +        public static ConcurrentBag<Gateway> GateWays = new ConcurrentBag<Gateway>();
Implemented your suggestions in 479ebbb. Take a look if you think it looks good now

2021-03-22 13:54 UTC, tjomson approved these changes
Implemented Mads' suggestions

2021-03-23 09:53 UTC, merged