Feature/live-updates
SimCorp/nats-topology-visualiser pull request #78
Opened 2021-05-18 11:29 UTC by SmillaDion

This branch contains a lot of new features for the live updates story.

* Refactored the backend API to a single endpoint (old ones are still there for testing/debugging)
* Fixed the time format in the status bar, DateTime object now gets formatted on the frontend
* The graph and its data now updates when reloading the page (F5), takes 5-10 seconds
* Added reload button so you can also refresh the graph without reloading the page itself

# How was this tested?

It wasn't - mostly frontend work, although we have changed the API to only have one endpoint. Not sure if that should be tested or not.

# Type of change

Please check all boxes that apply to this change below.

| Type                     | Applies ✅|
| ------------------------ | :-------: |
| Backend                  |     ✅     |
| Frontend                 |     ✅     |
| Github/Ci/Admin          |           |
| Documentation required   |           |

# Checklist

Please follow the checklist below and check all completed items as you work on the PR.

I have..
- [ ] performed a self-review of my own code
- [ ] commented my code, particularly in hard-to-understand areas
- [ ] written documentation
- [ ] added automated tests
- [ ] merged dependencies to `develop

2021-05-18 11:45 UTC, Maasdamind requested changes
This looks really good! Just have the above questions. Not that any changes should be made, just curious 👍

2021-05-18 11:45 UTC, Maasdamind commented on backend/Program.cs
>              drawablesProcessor = new DrawablesProcessor(eventParser.dataStorage);
Is there a way to update the data without having to instantiate these every time?

2021-05-18 11:45 UTC, Maasdamind commented on src/components/Graph/Graph.vue
> +      return ""
Should we maybe consider adding this to the controller in the backend instead? Not sure if it is really worth it though

2021-05-18 12:20 UTC, SmillaDion commented on backend/Program.cs
>              drawablesProcessor = new DrawablesProcessor(eventParser.dataStorage);
Honestly, neither Thomas or I know much about the backend... it was quite lucky that we even got it working simply by reinstantiating everything. So if someone with more backend knowledge has a better idea, they are free to refactor!

2021-05-18 12:27 UTC, SmillaDion commented on src/components/Graph/Graph.vue
> +      return ""
Hm perhaps but I think it may be too much of a hassle as we want all of the information in varz anyways, this is probably fine for now - though again, unless someone else has a good idea.

2021-05-18 13:46 UTC, Maasdamind commented on backend/Program.cs
>              drawablesProcessor = new DrawablesProcessor(eventParser.dataStorage);
Thats totally fine, might look into it after this is merged 🚀

2021-05-18 13:46 UTC, Maasdamind commented on src/components/Graph/Graph.vue
> +      return ""
I agree! let's keep it as is if it works fine 👍

2021-05-19 11:36 UTC, tjomson approved these changes
Niceeee

2021-05-19 11:42 UTC, merged